salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/CCI_Integration_Error_Retry__c.object-meta.xml
<CustomObject>
    <label>Integration Error Retry</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>ErrorLogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Retries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Integration_Procedure_Name__c.field-meta.xml
<CustomField>
    <fullName>Integration_Procedure_Name__c</fullName>
    <label>Integration Procedure Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Parent_Record_SFDC_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record_SFDC_ID__c</fullName>
    <description>Parent Salesforce Reference Object ID</description>
    <label>Parent Record SFDC ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Retry_Count__c.field-meta.xml
<CustomField>
    <fullName>Retry_Count__c</fullName>
    <defaultValue>0</defaultValue>
    <label>Retry Count</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Retry_Status__c.field-meta.xml
<CustomField>
    <fullName>Retry_Status__c</fullName>
    <label>Retry Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/System_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Name__c</fullName>
    <description>System integrating with</description>
    <label>System_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/CCI_Integration_System_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Endpoint Setting for the integration System with Vlocity</description>
    <label>Integration_System_Setting</label>
    <pluralLabel>Integration_System_Settings</pluralLabel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/System_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Name__c</fullName>
    <description>System Name</description>
    <label>System_Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/Transport_Error_Max_Retry__c.field-meta.xml
<CustomField>
    <fullName>Transport_Error_Max_Retry__c</fullName>
    <defaultValue>4</defaultValue>
    <description>Transport Error Max Retry</description>
    <label>Transport Error Max Retry</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

salesforce_sfdx/main/default/classes/CCI_FrmwrkRetryCalloutBatch.cls
/*********************************************************************************************
* @ClassName 				: CCI_FrmwrkRetryCalloutBatch
  @testClass				: None
* @Description 				: This batch class will intiate automatic retry of failed records.
* @Reason for Class Sharing : 
* @Author 					: SFDC
* @RevisionHistory 			: CH00
* @Version          Date              Changes made 
    CH00		    2/15/2022		  Initial Draft
***********************************************************************************************/

global class CCI_FrmwrkRetryCalloutBatch implements Database.Batchable<sObject>, Database.AllowsCallouts, Database.Stateful {
	
    private static final String STATUS_RESUBMISSION = 'Resubmission In Progress';
    private static final String PARENT_RECORD_SFDC_ID = 'Parent_Record_SFDC_ID';
    private static final String RETRY_RECORD_ID = 'Retry_Record_Id';
    global String serviceName;
    
    /*************************************************************************************
    @Description : Parametrized Constructor
	@Author 	 : SFDC
	@Params 	 : String serviceNameInput
	@Return 	 : None
    **************************************************************************************/
    public CCI_FrmwrkRetryCalloutBatch(String serviceNameInput) {
        serviceName = serviceNameInput;
    }
    
    /*************************************************************************************
    @Description : Start method of the Batch to return the Retry records which are in Resubmission in progress
	@Author 	 : SFDC
	@Params 	 : Database.BatchableContext BC
	@Return 	 : Database.QueryLocator
    **************************************************************************************/
    public Database.QueryLocator start(Database.BatchableContext BC){
        Integer maxRetries = CCI_FrmwrkRetryCalloutBatch.getRetryMasterData(serviceName);//retreiving master data for retry count from metadata.
        return Database.getQueryLocator([
            SELECT Id,Retry_Count__c,Retry_Status__c,
            System_Name__c,Integration_Procedure_Name__c,Parent_Record_SFDC_ID__c
            FROM CCI_Integration_Error_Retry__c 
            WHERE Retry_Count__c<=:maxRetries
            And Retry_Status__c=:STATUS_RESUBMISSION
            AND System_Name__c=:serviceName
        ]);
    }
	
    /*************************************************************************************
    @Description : Execute method of the Batch which will call the IP to retry
	@Author 	 : SFDC
	@Params 	 : Database.BatchableContext BC, List<CCI_Integration_Error_Retry__c> retryRecords
	@Return 	 : None
    **************************************************************************************/
    public void execute(Database.BatchableContext BC, List<CCI_Integration_Error_Retry__c> retryRecords){
        List<String> retryRecordsIdList = new List<String>();
        for(CCI_Integration_Error_Retry__c retryRecord:retryRecords){//loop start here..
            callIntegrationProcedure(retryRecord.Integration_Procedure_Name__c, 
                                     retryRecord.Parent_Record_SFDC_ID__c, retryRecord.Id);
        }
    }
    
    /*************************************************************************************
    @Description : Finish method of the Batch currently emty but can be used in future to write post processing logic
	@Author 	 : SFDC
	@Params 	 : Database.BatchableContext BC
	@Return 	 : None
    **************************************************************************************/
    public void finish(Database.BatchableContext BC){
    }
    
    /*************************************************************************************
    @Description : Get the Max Retry Count from Metadata
	@Author 	 : SFDC
	@Params 	 : String serviceName
	@Return 	 : Integer
    **************************************************************************************/
    public static Integer getRetryMasterData(String serviceName){
        CCI_Integration_System_Setting__mdt retryMasterData = CCI_Integration_System_Setting__mdt.getInstance(serviceName);
        return retryMasterData.Transport_Error_Max_Retry__c!=null ? (Integer)retryMasterData.Transport_Error_Max_Retry__c : 0;
    }
    
    /*************************************************************************************
    @Description : Used to call the integration procedure
	@Author 	 : SFDC
	@Params 	 : String IPName, String parentRecordId, String retryRecordId
	@Return 	 : None
    **************************************************************************************/
    private static void callIntegrationProcedure(String IPName, String parentRecordId, String retryRecordId) {
        Map<String, Object> ipInput = new Map<String, Object> ();
        Map<String, Object> ipOutput = new Map<String, Object> ();
        Map<String, Object> ipOptions = new Map<String, Object> ();
        ipInput.put(PARENT_RECORD_SFDC_ID, parentRecordId);
        ipInput.put(RETRY_RECORD_ID, retryRecordId);
        ipOutput = (Map<String, Object>) %vlocity_namespace%.IntegrationProcedureService.runIntegrationService(
                IPName, ipInput, ipOptions);
    }
}