salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/CCI_Integration_Error_Retry__c.object-meta.xml
<CustomObject>
    <label>Integration Error Retry</label>
    <nameField>
        <displayFormat>E-{0000000000}</displayFormat>
        <label>ErrorLogId</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Error Retries</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Error_Message__c.field-meta.xml
<CustomField>
    <fullName>Error_Message__c</fullName>
    <description>Error Message received from the integrating system</description>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Message_ID__c.field-meta.xml
<CustomField>
    <fullName>Message_ID__c</fullName>
    <description>Correlation Message ID</description>
    <label>Message ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Parent_Record_SFDC_ID__c.field-meta.xml
<CustomField>
    <fullName>Parent_Record_SFDC_ID__c</fullName>
    <description>Parent Salesforce Reference Object ID</description>
    <label>Parent Record SFDC ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Typical Status Values are - 
Pending
Processing
Processed
Error</description>
    <label>Status</label>
    <length>15</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_Error_Retry__c/fields/System_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Name__c</fullName>
    <description>System integrating with</description>
    <label>System_Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/classes/CCI_FrmwrkTransportErrorRetryTest.cls
/*********************************************************************************************
* @ClassName 				: CCI_FrmwrkTransportErrorRetryTest
  @testClass				: None
* @Description 				: Test class of CCI_FrmwrkRQRErrorRetrySchedulable
* @Reason for Class Sharing : 
* @Author 					: 
* @RevisionHistory 			: CH00
* @Version          Date              Changes made 
    CH00		    12/27/2021		  Initial Draft
***********************************************************************************************/
@isTest(SeeAllData = false)
public class CCI_FrmwrkTransportErrorRetryTest {
	
    /*************************************************************************************
    @Description : Validate the Retry IP
	@Author 	 : SFDC
	@Params 	 : None
	@Return 	 : None
    **************************************************************************************/
    @isTest public static void validateTransportErrorRetryFun(){
   

            Test.startTest();
            //Create Error Retry record
            CCI_Integration_Error_Retry__c obj = new CCI_Integration_Error_Retry__c();
            obj.Message_ID__c = 'Group_Upload';
            obj.Parent_Record_SFDC_ID__c = UserInfo.getUserId();
            obj.System_Name__c = 'apigee';
            obj.Error_Message__c = 'Test Error Message';
            obj.Status__c = 'Pending';
           	insert obj;
            
            Map<String, Object> inputMap = new Map<String, Object>();
            inputMap.put('ParentRecordId', obj.Parent_Record_SFDC_ID__c);
            inputMap.put('ErrorObjectLogId', obj.Id);
            inputMap.put('SystemName', obj.System_Name__c);
            inputMap.put('Path', '');
            inputMap.put('MessageID', obj.Message_ID__c);
            inputMap.put('Payload', '');
            inputMap.put('IntegrationProcedureName', 'Framework_HTTPGETCallout');
            
            CCI_FrmwrkTransportErrorRetry retryObj = new CCI_FrmwrkTransportErrorRetry();
            retryObj.invokeMethod('retryRequest', inputMap, new Map<String, Object>(), new Map<String, Object>());
            retryObj.invokeMethod('retryRequest', inputMap, new Map<String, Object>(), new Map<String, Object>());
            system.assert(obj != null);
            Test.stopTest();
  
    }
}