salesforce_sfdx/main/default/objects/CCI_Document__c/CCI_Document__c.object-meta.xml
<CustomObject>
    <description>This object will store the mandatory field required for P8 for retrieval/upload documents to P8 System</description>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/CCI_Integration_System_Setting__mdt.object-meta.xml
<CustomObject>
    <description>Endpoint Setting for the integration System with Vlocity</description>
    <label>Integration_System_Setting</label>
    <pluralLabel>Integration_System_Settings</pluralLabel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/Apex_Method_Name__c.field-meta.xml
<CustomField>
    <fullName>Apex_Method_Name__c</fullName>
    <description>Apex Method name to call when Use Apex checkbox is true</description>
    <label>Apex Method Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/Logging_Enabled__c.field-meta.xml
<CustomField>
    <fullName>Logging_Enabled__c</fullName>
    <defaultValue>true</defaultValue>
    <description>If checked, would audit and log all inbound and outbound payloads to the system</description>
    <inlineHelpText>If checked, would audit and log all inbound and outbound payloads to the system</inlineHelpText>
    <label>Logging Enabled</label>
    <type>Checkbox</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/Params__c.field-meta.xml
<CustomField>
    <fullName>Params__c</fullName>
    <label>Params</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/objects/CCI_Integration_System_Setting__mdt/fields/System_Name__c.field-meta.xml
<CustomField>
    <fullName>System_Name__c</fullName>
    <description>System Name</description>
    <label>System_Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

salesforce_sfdx/main/default/classes/CCI_FrmwrkHttpPostCalloutTest.cls
/*********************************************************************************************
* @ClassName 				: CCI_FrmwrkHttpPostCalloutTest
  @testClass				: None
* @Description 				: Test class of CCI_FrmwrkHttpPostCallout
* @Reason for Class Sharing : 
* @Author 					: SFDC
* @RevisionHistory 			: CH00
* @Version          Date              Changes made 
    CH00		    2/17/2022		  Initial Draft
***********************************************************************************************/
@isTest(SeeAllData = false)
public class CCI_FrmwrkHttpPostCalloutTest {
	@isTest private static void shouldInvokeUtilityMethod(){
        ContentVersion contentVersion = new ContentVersion(
            Title          = 'a picture',
            PathOnClient   = 'Pic.jpg',
            VersionData    = Blob.valueOf('Test Content'),
            IsMajorVersion = true);
        insert contentVersion;
        
        List<ContentDocument> documents = [SELECT Id, Title, LatestPublishedVersionId FROM ContentDocument];
        
        
        CCI_Document__c documentRecord = new CCI_Document__c();
        insert documentRecord;
        
        CCI_Integration_System_Setting__mdt p8ItegrationSetting = [
            SELECT Apex_Method_Name__c,Named_Credential__c,Logging_Enabled__c,
            Params__c,System_Name__c
            FROM CCI_Integration_System_Setting__mdt
            WHERE DeveloperName = 'P8DocumentUpload'
        ];
        
        //String payLoad='{"searchIndexes":[{"name":"CaseID","value":"00001023"},{"name":"ContractNumber","value":""}],"image":{"format":"application/txt","content":"base64string"},"objectStore":"MemAppOS","documentClass":"MEMAPP","documentType":"APPL","lineOfBusiness":"BCBS"}';
		//CCI_P8PostRequestWrapper reqWrapper = (CCI_P8PostRequestWrapper)JSON.deserialize(payload, CCI_HTTPPostRequestWrapper.class);
        CCI_P8PostRequestWrapper reqWrapper = new CCI_P8PostRequestWrapper();
        reqWrapper.objectStore = 'MemAppOS';
        reqWrapper.documentClass = 'MEMAPP';
        reqWrapper.documentType = 'APPL';
        reqWrapper.lineOfBusiness = 'BCBS';
        
        Set<CCI_P8PostRequestWrapper.cls_searchIndexes> searchIndexes = new Set<CCI_P8PostRequestWrapper.cls_searchIndexes>();
        CCI_P8PostRequestWrapper.cls_searchIndexes searchString = new CCI_P8PostRequestWrapper.cls_searchIndexes();
        searchString.name = 'CaseID';
        searchString.value = '00001023';
        searchIndexes.add(searchString);
        reqWrapper.searchIndexes = searchIndexes;
        
        CCI_P8PostRequestWrapper.cls_image imageData = new CCI_P8PostRequestWrapper.cls_image();
        imageData.content = 'base64string';
        imageData.format = 'application/jpg';
        reqWrapper.image = imageData;
        
        
        Map<String, Object> inputMap = new Map<String, Object>();
        inputMap.put('Payload', reqWrapper);
        inputMap.put('endpoint', p8ItegrationSetting.Named_Credential__c+p8ItegrationSetting.Params__c);
        inputMap.put('authorization', 'dummy token');
        inputMap.put('contentType', 'application/json');
        inputMap.put('additionalMethodArguments', 'contentDocumentId='+documents[0].Id+'&documentId='+documentRecord.Id);
        inputMap.put('utilityMethodName', p8ItegrationSetting.Apex_Method_Name__c);
        inputMap.put('isLoggingEnabled',p8ItegrationSetting.Logging_Enabled__c);
        inputMap.put('Service_Name', 'P8DocumentUpload');
        inputMap.put('Message_ID', 'dummyMessageId');
        inputMap.put('DynamicParams', 'dummyMessageId');
        Test.startTest();
        CCI_FrmwrkHttpPostCallout frmwrkPost = new CCI_FrmwrkHttpPostCallout();
        System.assert(frmwrkPost.invokeMethod('utilityMethod', inputMap, new Map<String, Object>(), new Map<String, Object>()));
        Test.stopTest();
    }
}