salesforce_sfdx/main/default/objects/CCI_Document__c/CCI_Document__c.object-meta.xml
<CustomObject>
    <description>This object will store the mandatory field required for P8 for retrieval/upload documents to P8 System</description>
    <label>Document</label>
    <nameField>
        <displayFormat>Doc-{0000}</displayFormat>
        <label>Document Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

salesforce_sfdx/main/default/objects/CCI_Document__c/fields/Document_Id_Ext__c.field-meta.xml
<CustomField>
    <fullName>Document_Id_Ext__c</fullName>
    <description>This will store the response received from the P8 after upload.</description>
    <externalId>true</externalId>
    <label>Document Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

salesforce_sfdx/main/default/classes/CCI_DownloadDocumentControllerTest.cls
/*********************************************************************************************
* @ClassName 				: CCI_DownloadDocumentControllerTest
  @testClass				: Test Class for CCI_DownloadDocumentController
* @Description 				: Test Class
* @Reason for Class Sharing : 
* @Author 					: SFDC
* @RevisionHistory 			: NK
* @Version          Date              Changes made 
    NK		    02/14/2022		  Initial Draft
***********************************************************************************************/
@isTest
public class CCI_DownloadDocumentControllerTest {
	@isTest 
    public static void getDownloadDocumentDetails(){
        CCI_Document__c doc = new CCI_Document__c();
        //doc.Document_Id_Ext__c ='asded-ffss-sdsds-2344';
        insert doc;
        CCI_DownloadDocumentController.DocumentWrapper docWrap = new CCI_DownloadDocumentController.DocumentWrapper();
        docWrap = CCI_DownloadDocumentController.getDownloadDocumentDetails(doc.Id);
        doc.Document_Id_Ext__c ='asded-ffss-sdsds-2344';
        update doc;
        CCI_DownloadDocumentController.DocumentWrapper docWrap2 = new CCI_DownloadDocumentController.DocumentWrapper();
        docWrap2 = CCI_DownloadDocumentController.getDownloadDocumentDetails(doc.Id);
    }
}